defmodule CopilotLv.Repo.Migrations.AddSessionStoreDbTables do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:session_refs, primary_key: false) do
      add :session_id,
          references(:sessions, column: :id, name: "session_refs_session_id_fkey", type: :text),
          null: false

      add :created_at, :text
      add :turn_index, :bigint
      add :ref_value, :text, null: false
      add :ref_type, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:session_refs, [:session_id, :ref_type, :ref_value],
             name: "session_refs_unique_ref_per_session_index"
           )

    create table(:session_files, primary_key: false) do
      add :session_id,
          references(:sessions, column: :id, name: "session_files_session_id_fkey", type: :text),
          null: false

      add :first_seen_at, :text
      add :turn_index, :bigint
      add :tool_name, :text
      add :file_path, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:session_files, [:session_id, :file_path],
             name: "session_files_unique_file_per_session_index"
           )

    alter table(:checkpoints) do
      add :overview, :text
      add :history, :text
      add :work_done, :text
      add :technical_details, :text
      add :important_files, :text
      add :next_steps, :text
    end

    create unique_index(:checkpoints, [:session_id, :number],
             name: "checkpoints_unique_checkpoint_per_session_index"
           )
  end

  def down do
    drop_if_exists unique_index(:checkpoints, [:session_id, :number],
                     name: "checkpoints_unique_checkpoint_per_session_index"
                   )

    alter table(:checkpoints) do
      remove :next_steps
      remove :important_files
      remove :technical_details
      remove :work_done
      remove :history
      remove :overview
    end

    drop_if_exists unique_index(:session_files, [:session_id, :file_path],
                     name: "session_files_unique_file_per_session_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `session_files` table without the `session_files_session_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:session_files)

    drop_if_exists unique_index(:session_refs, [:session_id, :ref_type, :ref_value],
                     name: "session_refs_unique_ref_per_session_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `session_refs` table without the `session_refs_session_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:session_refs)

    alter table(:sessions) do
      remove :starred
      remove :config_dir
      remove :agent
      remove :hostname
      # This is the `down` migration of the statement:
      #
      #     remove :copilot_session_id
      #

      # add :copilot_session_id, :text
    end
  end
end