defmodule CopilotLv.Repo.Migrations.AddImportFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:sessions) do
      add :summary, :text
      add :git_root, :text
      add :branch, :text
      add :copilot_version, :text
      add :event_count, :bigint
      add :source, :text
      add :imported_at, :utc_datetime_usec
    end

    alter table(:events) do
      add :parent_event_id, :text
    end

    create table(:checkpoints, primary_key: false) do
      add :session_id,
          references(:sessions, column: :id, name: "checkpoints_session_id_fkey", type: :text),
          null: false

      add :content, :text
      add :filename, :text
      add :title, :text
      add :number, :bigint, null: false
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `checkpoints` table without the `checkpoints_session_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:checkpoints)

    alter table(:events) do
      remove :parent_event_id
    end

    alter table(:sessions) do
      remove :imported_at
      remove :source
      remove :event_count
      remove :copilot_version
      remove :branch
      remove :git_root
      remove :summary
    end
  end
end