defmodule CopilotLv.Repo.Migrations.AddArtifactsAndTodos do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:session_todos, primary_key: false) do
      add :session_id,
          references(:sessions, column: :id, name: "session_todos_session_id_fkey", type: :text),
          null: false

      add :depends_on, {:array, :text}, default: []
      add :status, :text
      add :description, :text
      add :title, :text, null: false
      add :todo_id, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:session_todos, [:session_id, :todo_id],
             name: "session_todos_unique_todo_per_session_index"
           )

    create table(:session_artifacts, primary_key: false) do
      add :session_id,
          references(:sessions,
            column: :id,
            name: "session_artifacts_session_id_fkey",
            type: :text
          ), null: false

      add :artifact_type, :text, null: false
      add :size, :bigint
      add :content_hash, :text, null: false
      add :content, :text
      add :path, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:session_artifacts, [:session_id, :path],
             name: "session_artifacts_unique_path_per_session_index"
           )
  end

  def down do
    drop_if_exists unique_index(:session_artifacts, [:session_id, :path],
                     name: "session_artifacts_unique_path_per_session_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `session_artifacts` table without the `session_artifacts_session_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:session_artifacts)

    drop_if_exists unique_index(:session_todos, [:session_id, :todo_id],
                     name: "session_todos_unique_todo_per_session_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `session_todos` table without the `session_todos_session_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:session_todos)
  end
end