defmodule CopilotLv.Repo.Migrations.AddSessionTitle do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:sessions) do
      add :title, :text
    end
  end

  def down do
    alter table(:sessions) do
      remove :title
    end
  end
end