defmodule CopilotLv.Repo.Migrations.CreateSessions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:usage_entries, primary_key: false) do
      add :session_id,
          references(:sessions, column: :id, name: "usage_entries_session_id_fkey", type: :text),
          null: false

      add :timestamp, :utc_datetime_usec
      add :duration_ms, :bigint
      add :initiator, :text
      add :cost, :float
      add :cache_write_tokens, :bigint
      add :cache_read_tokens, :bigint
      add :output_tokens, :bigint
      add :input_tokens, :bigint
      add :model, :text
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:sessions, primary_key: false) do
      add :stopped_at, :utc_datetime_usec
      add :started_at, :utc_datetime_usec
      add :status, :text
      add :model, :text
      add :cwd, :text, null: false
      add :copilot_session_id, :text
      add :id, :text, null: false, primary_key: true
    end

    create table(:events, primary_key: false) do
      add :session_id,
          references(:sessions, column: :id, name: "events_session_id_fkey", type: :text),
          null: false

      add :sequence, :bigint, null: false
      add :timestamp, :utc_datetime_usec
      add :data, :map, default: %{}
      add :event_id, :text
      add :event_type, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `events` table without the `events_session_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:events)

    drop table(:sessions)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `usage_entries` table without the `usage_entries_session_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:usage_entries)
  end
end